version: '3.8'

services:
  # База данных
  postgres:
    image: postgres:15-alpine
    container_name: mindarity-postgres
    environment:
      POSTGRES_DB: mindarity
      POSTGRES_USER: mindarity_user
      POSTGRES_PASSWORD: mindarity_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindarity-network

  # Redis для кэширования и сессий
  redis:
    image: redis:7-alpine
    container_name: mindarity-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mindarity-network

  # Elasticsearch для поиска
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: mindarity-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mindarity-network

  # MinIO для хранения файлов
  minio:
    image: minio/minio:latest
    container_name: mindarity-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mindarity-network

  # Keycloak для аутентификации
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: mindarity-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev
    networks:
      - mindarity-network

  # Backend приложение
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindarity-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://mindarity_user:mindarity_password@postgres:5432/mindarity
      REDIS_URL: redis://redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      KEYCLOAK_URL: http://keycloak:8080
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - minio
      - keycloak
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mindarity-network

  # Frontend приложение
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mindarity-frontend
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_KEYCLOAK_URL: http://localhost:8080
    ports:
      - "5173:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mindarity-network

  # Nginx для reverse proxy
  nginx:
    image: nginx:alpine
    container_name: mindarity-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
      - keycloak
      - minio
    networks:
      - mindarity-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  minio_data:

networks:
  mindarity-network:
    driver: bridge 