version: '3.8'

services:
  backend:
    build: null
    image: node:20
    working_dir: /app
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      CORS_ORIGIN: http://localhost:5173,http://dev.mindarity.ru
      # Dev-specific settings
      DATABASE_SYNCHRONIZE: "true"
      LOGGING: "true"
      DEBUG: "true"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: mindarity_user
      DATABASE_PASSWORD: mindarity_password
      DATABASE_NAME: mindarity_dev
      DATABASE_URL: postgresql://mindarity_user:mindarity_password@postgres:5432/mindarity_dev
      MINIO_PUBLIC_URL: http://localhost:9000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run start:dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-dev.rule=Host(`dev.mindarity.ru`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend-dev.loadbalancer.server.port=3000"

  frontend:
    build: null
    image: node:20
    working_dir: /app
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
      VITE_KEYCLOAK_URL: http://localhost:8080
      VITE_MINIO_PUBLIC_URL: http://localhost:9000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=Host(`dev.mindarity.ru`)"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=5173"

  nginx:
    environment:
      NGINX_ENV: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-dev.rule=Host(`dev.mindarity.ru`)"
      - "traefik.http.services.nginx-dev.loadbalancer.server.port=80"

  # Dev-specific services
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mindarity-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog-dev.rule=Host(`dev.mindarity.ru`) && PathPrefix(`/mail`)"
      - "traefik.http.services.mailhog-dev.loadbalancer.server.port=8025"

  # Development database with sample data
  postgres:
    environment:
      POSTGRES_DB: mindarity_dev
      POSTGRES_USER: mindarity_user
      POSTGRES_PASSWORD: mindarity_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
