global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: mindarity
    environment: production

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Backend application
  - job_name: 'mindarity-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: /monitoring/metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    metrics_path: /metrics
    scrape_interval: 15s

  # Blackbox exporter (external monitoring)
  - job_name: 'blackbox'
    static_configs:
      - targets:
        - 'https://mindarity.ru'
        - 'https://mindarity.ru/api'
        - 'https://mindarity.ru/auth'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 60s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Service discovery for dynamic targets
  - job_name: 'docker-swarm'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 2375
        filters:
          - name: name
            values: ['.*']
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_swarm_task_name]
        target_label: task
      - source_labels: [__meta_docker_container_label_com_docker_swarm_node_id]
        target_label: node

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

# Recording rules
rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml" 